version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y hugo
  build:
    commands:
      - hugo
  post_build:
    commands:
      - aws s3 sync public/ s3://portfolio-site-6/ --delete

artifacts:
  files:
    - '**/*'
